### ISSUE TITLE
change the search title to accurately reflect [docker]

### ISSUE THREAD

**Issue by ZoomyCat** [yobasystems/gitlab-runner#2]
Here I am looking for how to get gitlab-runner working in alpine and the title was simply misleading and wasted my time. I'd appreciate if you updated the readme so the search result reflects that this is for inside docker...

**Comment by dominictayloruk** [comment]
Well i'm sorry you feel that way.
Let me just get a few points across;

1. The title isn't misleading as it is gitlab runner, and the sub-title is 'Gitlab Runner on Alpine Linux [Docker]'. If you couldn't figure this out and thought an issue would be applicable then i think you are mistaken.
2. If you read through the dockerfile, then you would have seen the steps required to get gitlab runner working on Alpine without using docker.
3. The readme clearly states that this is for Docker!
4. If you don't have anything constructive to contribute, then simply fuck off!
