### ISSUE TITLE
status=Error decoding json payload json: cannot unmarshal number into Go struct field JobResponse.id of type int

### ISSUE THREAD

**Issue by hunnguye** [yobasystems/gitlab-runner#3]
# Observation
I was using the image on my RPI. The image does run and registration against gitlab works fine.

However when i started a test pipeline, the following error appears:
```
WARNING: Checking for jobs... failed
status=Error decoding json payload json: cannot unmarshal number 2638377850 into Go struct field JobResponse.id of type int
```

To be honest i am not too familiar with the gitlab runner yet. However in the official repository people seem to have already discussed this problem (https://gitlab.com/gitlab-org/gitlab-runner/-/issues/28151)

# Solution

I just updated the Version of the runner from the current version (14.8.1) to 14.9.0 and rebuild the image. Afterwards i could run the runner without problems on an example pipeline.

**Comment by dominictayloruk** [comment]
Should be fixed in 15.2.1
