### ISSUE TITLE
gitlab runner on armv7

### ISSUE THREAD

**Issue by Skill3t** [yobasystems/gitlab-runner#4]
Hi if i start the image 
i get the error 
runner The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

if i run yobasystems/gitlab-runner:16.4.0-armhf or the yobasystems/gitlab-runner:latest.

i Use a armV7 (32bit) System with docker "Docker version 20.10.21-ce"

So the doku https://github.com/yobasystems/gitlab-runner#%EF%B8%8F-architectures looks like the platfrom should be supported. 
So ist armv7 is still suported?

**Comment by dominictayloruk** [comment]
Looks like the image has been incorrectly tagged, i'll look into it, update & push a new image.

**Comment by dominictayloruk** [comment]
Found the cause. Fix coming shortly.
https://github.com/yobasystems/alpine-mariadb/issues/71#issuecomment-1898849715

**Comment by dominictayloruk** [comment]
New image pushed to https://hub.docker.com/r/yobasystems/gitlab-runner

**Comment by dominictayloruk** [comment]
This is fixed
